### ISSUE TITLE
Feature request: more fine-grained control of what to notify on

### ISSUE THREAD

**Issue by shinmai** [sszczep/Flo#1]
Currently the only options to limit what get's posted to slack is GloBoards' webhook settings (Board, Column, Card, Comment). Even if I only select Column and Card, and create a new card, assign it some labels and add some tasks, I get one message on slack each for the creation, the label change and one for each added task. I'd love to be able to select to only get slack messages for for instance when card is moved to a new column, when assignments are changed and when cards are created.

**Comment by sszczep** [comment]
Thanks for the feedback. I can implement that feature, however it may take some time. I will keep you updated in this thread.
