### ISSUE TITLE
flo command in Slack

### ISSUE THREAD

**Issue by dunajski** [sszczep/Flo#2]
I've got problem with slash commands. I mean, I added app to workspace (at tabs Flo bot appeared) but when i type */flo help* or simple */flo* get hint with.

> Darn - that slash command didn't work. Feel free to give it another go, or you can manage the integration (and view who installed it) at Flo.

Am i doing something wrong? I've attached bot to new Slack channel, nothing happened. 😞

**Comment by sszczep** [comment]
#3 follow there for info.
