### ISSUE TITLE
floapp.tk is not reachable for installation 

### ISSUE THREAD

**Issue by An-Dang** [sszczep/Flo#3]
I just want to install Flo for our Slack. Unfortunately after clicking install the link: https://floapp.tk/slack/ is not reachable.

**Comment by sszczep** [comment]
I’m aware of that problem. I need to refresh domain and ssl certificate. Might be done even today.

**Comment by An-Dang** [comment]
Nice, thanks! :)

**Comment by An-Dang** [comment]
Still not available.

**Comment by sszczep** [comment]
Fixed, should be working now.

**Comment by dunajski** [comment]
Flo bot works for me now.
