### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by jmanooch** [sszczep/Flo#4]
For some reason Glow shows Bad Request as the response to all notifcations via the webhook.

**Comment by sszczep** [comment]
I'll definitely look at it. Thanks for informing me.

**Comment by jmanooch** [comment]
Let me know if you need anymore feedback on this.

**Comment by sszczep** [comment]
Sorry for such a delay. I've been moving project to other server. Everything should be working now. Please let me know.

**Comment by jmanooch** [comment]
Same issue alas. 

![Screenshot 2019-10-27 at 02 05 08](https://user-images.githubusercontent.com/2614501/67627546-72e90980-f85e-11e9-88a4-9aac87c86319.png)

![Screenshot 2019-10-27 at 02 04 37](https://user-images.githubusercontent.com/2614501/67627549-78465400-f85e-11e9-9d26-2a86d869678b.png)

**Comment by sszczep** [comment]
Are you sure you configured everything properly? Please show me configuration of your webhook

**Comment by jmanooch** [comment]
![Screenshot 2019-10-27 at 02 15 07](https://user-images.githubusercontent.com/2614501/67627613-b55f1600-f85f-11e9-8303-42d1093e9bb7.png)
![Screenshot 2019-10-27 at 02 15 48](https://user-images.githubusercontent.com/2614501/67627614-b85a0680-f85f-11e9-9f51-0aba763c2a11.png)

**Comment by jmanooch** [comment]
Updated the secret just before checking 10 mins ago, before new error message.

**Comment by sszczep** [comment]
Try using SSL verification. Has it been working ever before?

**Comment by jmanooch** [comment]
Just tried with SSL, same error message (bad request). Hasn't ever worked.

**Comment by jmanooch** [comment]
We have a vanilla Slack + globoards setup.

**Comment by jmanooch** [comment]
Happy to add any more details as you need.

**Comment by base2data** [comment]
Any thoughts on this?
