### ISSUE TITLE
Bug: timeout when connecting to a Slack workplace

### ISSUE THREAD

**Issue by JoelleCastelli** [sszczep/Flo#5]
Hi, it looks like there's a problem when linking Flo to a Slack workspace: during the installation process and after allowing the communication between Flo and my workspace, the request ends with a timeout error. I've tried on several browsers (Firefox, Chrome, Opera) both using corporate Wi-Fi and personnal 4G.

Is Flo still maintained?

**Comment by stefanbajic94** [comment]
I am experiencing the same issue.

**Comment by sszczep** [comment]
Thank you for Your feedback. Unluckily, my server subscription time ran out and im thinking about renewal.

**Comment by sszczep** [comment]
I'm sorry but I've decided not to maintain this project anymore. Feel free to create a fork and continue support.
